extends Control


#  [DOCSTRING]


#  [SIGNALS]


#  [ENUMS]
enum ColorOptions {
	PL3, # PRIMARY LIGHT 3
	PL2, # PRIMARY LIGHT 2
	PL1, # PRIMARY LIGHT 1
	PB,  # PRIMARY BASE
	PD1, # PRIMARY DARK 1
	PD2, # PRIMARY DARK 2
	PD3, # PRIMARY DARK 3
	SL3, # SECONDARY LIGHT 3
	SL2, # SECONDARY LIGHT 2
	SL1, # SECONDARY LIGHT 1
	SB,  # SECONDARY BASE
	SD1, # SECONDARY DARK 1
	SD2, # SECONDARY DARK 2
	SD3, # SECONDARY DARK 3
	RED, # FIXED COLORS
	GREEN, # FIXED COLORS
	BLACK, # FIXED COLORS
	WHITE, # FIXED COLORS
	LIGHTGRAY, # FIXED COLORS
	DARKGRAY, # FIXED COLORS
}


#  [CONSTANTS]


#  [EXPORTED_VARIABLES]
export(ColorOptions) var selected_color: int = ColorOptions.PL1


#  [PUBLIC_VARIABLES]


#  [PRIVATE_VARIABLES]


#  [ONREADY_VARIABLES]


#  [OPTIONAL_BUILT-IN_VIRTUAL_METHOD]
#func _init() -> void:
#	pass


#  [BUILT-IN_VIRTUAL_METHOD]


#  [REMAINIG_BUILT-IN_VIRTUAL_METHODS]
#func _process(_delta: float) -> void:
#	pass


#  [PUBLIC_METHODS]


#  [PRIVATE_METHODS]
 

#  [SIGNAL_METHODS]
